config/routes.rb
Rails.application.routes.draw do
  resources :groups do
    member do
      post :join
      post :quit
    end
    resources :posts
  end

  namespace :account do
    resources :groups
    resources :posts
  end

  devise_for :users

  root to: 'groups#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :owner, class_name: 'User', foreign_key: :user_id
  has_many :posts
  has_many :group_users
  has_many :members, through: :group_users, source: :user
  validates_presence_of :title

  after_create :join_owner_to_group

  def editable_by?(user)
    user && user == owner
  end

  def join_owner_to_group
    members << owner
  end
end

app/models/group_user.rb
class GroupUser < ApplicationRecord
  belongs_to :group
  belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :group, counter_cache: true
  validates_presence_of :content

  belongs_to :author, class_name: 'User', foreign_key: :user_id

  scope :recent, -> { order(updated_at: :desc) }

  def editable_by?(user)
    user && user == author
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  has_many :groups
  has_many :posts

  has_many :group_users
  has_many :participated_groups, through: :group_users, source: :group

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates_presence_of :name

  def join!(group)
    participated_groups << group
  end

  def quit!(group)
    participated_groups.delete(group)
  end

  def is_member_of?(group)
    participated_groups.include?(group)
  end
end

app/controllers/account/groups_controller.rb
class Account::GroupsController < ApplicationController

  def index
    @groups = current_user.participated_groups.order(posts_count: :desc)
  end
end

app/controllers/account/posts_controller.rb
class Account::PostsController < ApplicationController

  def index
    @posts = current_user.posts.recent
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :authenticate_user!, except: %i[index show]
  before_action :find_group, only: %i[show edit update destroy]

  def index
    @groups = Group.all
  end

  def new
    @group = Group.new
  end

  def create
    @group = current_user.groups.build(group_params)
    if @group.save
      redirect_to groups_path, notice: 'create success'
    else
      render :new
    end
  end

  def show
    @posts = @group.posts
  end

  def edit
    render :new
  end

  def update
    if @group.update(group_params)
      redirect_to groups_path, notice: 'update success'
    else
      render :new
    end
  end

  def destroy
    @group.destroy
    redirect_to groups_path, notice: 'delete success'
  end

  def join
    @group = Group.find(params[:id])
    if !current_user.is_member_of?(@group)
      current_user.join!(@group)
    else
      flash[:notice] = 'You already joined this group.'
    end
    redirect_to group_path(@group)
  end

  def quit
    @group = Group.find(params[:id])
    if current_user.is_member_of?(@group)
      current_user.quit!(@group)
    else
      flash[:notice] = 'You are not member of this group.'
    end
    redirect_to group_path(@group)
  end

  private

  def group_params
    params.require(:group).permit(:title, :description)
  end

  def find_group
    @group = Group.find(params[:id])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!
  before_action :find_group, only: %i[new create edit update destroy]
  before_action :find_post, only: %i[edit update destroy]
  before_action :member_required, only: %i[new create]

  def new
    @post = @group.posts.build
  end

  def create
    @post = @group.posts.new(post_params)
    @post.author = current_user
    if @post.save
      redirect_to group_path(@group), notice: 'create success'
    else
      render :new
    end
  end

  def edit
    render :new
  end

  def update
    if @post.update(post_params)
      redirect_to group_path(@group), notice: 'update success'
    else
      render :new
    end
  end

  def destroy
    @post.destroy
    redirect_to group_path(@group), notice: 'delete success'
  end

  private

  def post_params
    params.require(:post).permit(:content)
  end

  def find_group
    @group = Group.find(params[:group_id])
  end

  def find_post
    @post = current_user.posts.find(params[:id])
  end

  def member_required
    if !current_user.is_member_of?(@group)
      redirect_to group_path(@group), notice: 'You are not member of this group!'
    end
  end
end

app/views/groups/index.html.erb
  <div>
    <%= link_to 'New group', new_group_path, class: 'btn btn-outline-info' %>
  </div>

  <table class='table'>
    <thead>
      <tr>
        <td> # </td>
        <td>Title</td>
        <td>Description</td>
        <td>Owner</td>
        <td>Action</td>
      </tr>
    </thead>

    <tbody id='groups'>
      <% @groups.each do |group| %>
      <tr>
        <td> <%= group.id %> </td>
        <td><%= link_to group.title, group_path(group) %></td>
        <td><%= group.description %></td>
        <td><%= group.owner.name %></td>
        <td>
          <% if current_user && group.editable_by?(current_user) %>
          <%= link_to 'Edit', edit_group_path(group), class: 'btn btn-sm btn-outline-primary' %>
          <%= link_to 'Delete', group_path(group), class: 'btn btn-sm btn-outline-danger', method: 'delete', data: { confirm: 'Are you sure?' } %>
          <% end %>
        </td>
      </tr>
      <% end %>
    </tbody>
  </table>

app/views/groups/new.html.erb
<%= simple_form_for @group do |f| %>
  <%= f.input :title %>
  <%= f.input :description %>
  <%= f.button :submit, class: 'btn btn-primary' %>
  <%= link_to 'Back', groups_path %>
<% end %>

app/views/groups/show.html.erb
<div class="group">
  <% if current_user && @group.editable_by?(current_user) %>
  <%= link_to 'Edit', edit_group_path(@group), class: 'btn btn-sm btn-primary' %>
  <% end %>

  <% if current_user %>
    <% if current_user.is_member_of?(@group) %>
      <%= link_to 'Quit Group', quit_group_path(@group), method: :post, class: 'btn btn-sm btn-outline-warning' %>
    <% else %>
      <%= link_to 'Join Group', join_group_path(@group), method: :post, class: 'btn btn-sm btn-outline-success' %>
    <% end %>
  <% end %>

  <%= link_to 'New Post', new_group_post_path(@group), class: 'btn btn-sm btn-info' if current_user.present? && current_user.is_member_of?(@group) %>
</div>

<h2><%= @group.title %></h2>
<p><%= @group.description %></p>

<table class="table">
  <tbody>
    <% @posts.each do |post| %>
    <tr>
      <td>
      <span class="author"><strong>Author: <%= post.author.name %></strong></span>
      <p><%= post.content %></p>
      </td>
      <% if current_user && post.editable_by?(current_user) %>
      <td>
        <%= link_to 'Edit', edit_group_post_path(post.group, post), class: 'btn btn-sm btn-outline-primary' %>
        <%= link_to 'Delete', group_post_path(post.group, post), class: 'btn btn-sm btn-outline-danger', method: 'delete', data: { confirm: 'Are you sure?' } %>
      </td>
      <% end %>
    </tr>
    <% end %>
  </tbody>
</table>

<div>
  <%= link_to 'Back to Group', root_path, class: 'btn btn-outline-secondary' %>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light" style="background-color: #e3f2fd;">
    <div class="d-flex flex-grow-1">
        <span class="w-100 d-lg-none d-block"></span>
        <%= link_to 'Groups List', groups_path, class: 'navbar-brand' %>
    </div>

    <div class="collapse navbar-collapse flex-grow-1 text-right">
      <ul class="navbar-nav ml-auto flex-nowrap">
      <%#= link_to 'Admin', admin_products_path, class: 'navbar-brand' %>

      <% if current_user %>
        <span class="navbar-brand"><%= current_user.name %></span>
        <%= link_to 'My Groups', account_groups_path, class: 'navbar-brand' %>
        <%= link_to 'My Posts', account_posts_path, class: 'navbar-brand' %>
        <%= link_to 'Logout', destroy_user_session_path, method: :delete, class: 'navbar-brand' %>
      <% else %>
        <span class="navbar-brand">
        <%= link_to 'Signup', new_user_registration_path, class: 'navbar-brand' %>
        <%= link_to 'Login', new_user_session_path, class: 'navbar-brand' %>
        </span>
      <% end %>
      </ul>
    </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Groupme</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= render 'layouts/header' %>
    <div class="container">
      <%= flash[:notice] %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/posts/new.html.erb
<%= simple_form_for [@group, @post] do |f| %>
  <%= f.input :content %>
  <%= f.button :submit, class: 'btn btn-primary' %>
<% end %>